# Makefile strutture 

all: Repository.o File_Location.o Location.o File_Condition.o Lista_Prenotazioni.o

Repository.o: Repository.cpp 
	g++ -c Repository.cpp

File_Location.o: File_Location.cpp 
	g++ -c File_Location.cpp

Location.o: Location.cpp 
	g++ -c Location.cpp

File_Condition.o: File_Condition.cpp 
	g++ -c File_Condition.cpp

Lista_Prenotazioni.o: Lista_Prenotazioni.cpp 
	g++ -c Lista_Prenotazioni.cpp

clean :
	-@rm *.o

# fine Makefile
