# Makefile socket 

all: Socket_Attivo.o Socket_Passivo.o

Socket_Attivo.o: Socket_Attivo.cpp
	g++ -c Socket_Attivo.cpp

Socket_Passivo.o: Socket_Passivo.cpp
	g++ -c Socket_Passivo.cpp

clean :
	-@rm *.o

# fine Makefile
