client: 
	g++ ../lanciaClients.cpp  ../../../../socket/Socket_Attivo.o ../../../../src_CL/Client.cpp ../../../../utility/interprete.cpp ../../../../utility/msg_err.cpp -o client

clean :
	-@rm *.o client

