fs: lanciaFS.o 
	g++ lanciaFS.cpp ../../../src_FS/FS.o ../../../socket/Socket_Passivo.o ../../../socket/Socket_Attivo.o ../../../utility/msg_err.o ../../../utility/interprete.o -lpthread -o fs

clean :
	-@rm *.o fs

